### ISSUE TITLE
Weekly Scrum [2024/11/09]

### ISSUE THREAD

**Issue by EvanB213** [Lubbree/ProductReview#21]
Each team member should post a comment including their own contributions for this week, what they will be working on next week, and the links to the relevant Github Issues (open or closed).

**Comment by Lubbree** [comment]
Last week I:
- set up the github
- set up the azure
- got the basic spring configs and classes into the repository

This week I:
- set up the Kanban
- created the home page (#28)
- created the Product Controller and Repository (#11)
- implemented some http request integration tests (#22)

**Comment by EvanB213** [comment]
This week, I:

- created unit tests for each basic class (#13 , #14 , #15 ) 
- created a database schema for the current implementation (#7 )
- updated some functionality for basic classes (#9 )
- suggested a persistent database and did research into associated testcontainers functionality (#5 )

Next week, I will:

- finalize decision of persistent database and begin implementation (#33 )
-

**Comment by MatthewKhoury** [comment]
This week, I:


- Set up the google folder repository
- Made the backend files 
- did the uml diagram
- updated the readME


Next week, I will:

- 
Update the readMe and UML diagrams to accommodate new changes 
- I will update the controller class to have more features 
- create/help create a product page
- create a user account system
