### ISSUE TITLE
Weekly Scrum [2024-11-24]

### ISSUE THREAD

**Issue by EvanB213** [Lubbree/ProductReview#43]
Each team member should post a comment including their own contributions for this week, what they will be working on next week, and the links to the relevant Github Issues (open or closed).

**Comment by Lubbree** [comment]
This week, I:
- Set up the azure server (#31)
- Set up Test Containers (#32)
- Help the switch to PostgreSQL (#33)

Next week, I will:
- Work on front-end features
- Add more tests

**Comment by MatthewKhoury** [comment]
This week, I:


-added log in and create account features #39 
-updated UML diagram

Next week, I will:

-add front end for adding reviews
-add front end for adding products
-add back end for adding reviews
-add back end for adding products

**Comment by bellaville** [comment]
This week I:

- added create account and login pages to the front end #39 
- Implemented the ability for a user to login and logout #39
- worked on controllers #18 

Next week I will:

- Help with adding review functionality #35 
- Add additional user functionality #37
#52
